import types
import importlib
from pathlib import Path
import textwrap

BASE_DIR = Path(__file__).resolve().parent
stub_dir = BASE_DIR / "python" / "app" / "video_engine"


def inject_doc_into_pyi(stub_path: Path, doc: str):
    if not stub_path.exists():
        return

    content = stub_path.read_text()

    doc = textwrap.dedent(doc).strip()
    doc_block = f'"""\n{doc}\n"""\n\n'

    if content.lstrip().startswith('"""'):
        return

    print(f"Injecting docstring into {stub_path}")
    stub_path.write_text(doc_block + content)


def main():
    import app.video_engine

    module = app.video_engine

    if module.__doc__:
        inject_doc_into_pyi(stub_dir / "__init__.pyi", module.__doc__)
    for name in getattr(module, "__all__", []):
        # __all__ is usually a string name → import actual module

        try:
            sub_module = importlib.import_module(name, module.__name__)
        except ImportError:
            continue

        if not isinstance(sub_module, types.ModuleType):
            continue

        docs = sub_module.__doc__
        print(docs)
        if not docs:
            continue

        # stub_path = stub_dir / name / "__init__.pyi"
        stub_path = stub_dir / f"{name}.pyi"

        inject_doc_into_pyi(stub_path, docs)


# Not the best practices here but let's add the "__init__.py" for every submodule if it doesn't exist
def add_init_py_to_submodules():
    def add_init_py(sub_path: Path):
        init_file = sub_path / "__init__.py"
        if not init_file.exists():
            print(f"Creating {init_file}")
            init_file.write_text(
                "# This file is automatically generated by inject_docstring.py\n# ruff: noqa: E501, F401, F403, F405\n\n"
            )

    add_init_py(stub_dir)
    # for submodule in stub_dir.iterdir():
    #     if submodule.is_dir():
    #         add_init_py(submodule)


if __name__ == "__main__":
    main()
    # add_init_py_to_submodules()
